### ISSUE TITLE
Upgrade to later rust min version, revert MaybeUninit workaround

### ISSUE THREAD

**Issue by erlepereira** [AltF02/x11-rs#102]
This is a placeholder for future updates.

We introduced a workaround for MaybeUninit changes discussed in #101 . This currently only affects those using older versions of rust. 

[wiki reference, placeholder](https://github.com/erlepereira/x11-rs/wiki)

**Comment by erlepereira** [comment]
the new version of pkg-config - v0.3.15 .. is triggering build errors on rust 1.24.1
additionally  pkg-config list v1.28+ as minimum supported version, might need to bump up minimum version  before releasing an updated crate
[Build fails for version 1.24.1, works for nightly + stable](https://travis-ci.org/erlepereira/x11-rs/builds/571099128)

**Comment by est31** [comment]
@erlepereira there is no need to bump the MSRV because of dependencies. All you need to do is pin the version in travis.yml. I've made a PR to do this here: #103

Also yes, eventually the maybe-uninit dependency should be removed as the MSRV is bumped but that shouldn't happen soon IMO but maybe in 6 months or so (ultimately it's your choice ofc).
