### ISSUE TITLE
Xlib::open takes up a significant amount of the binary

### ISSUE THREAD

**Issue by notgull** [AltF02/x11-rs#168]
By running `cargo bloat` on a binary I created with `winit`, I can see that running `x11_dl::xlib::Xlib::open` takes up about 3.6% of the binary's total space, significantly more than any other function. It would be nice if it took up less space.

**Comment by AltF02** [comment]
Hm, this is on winit or x11 to optimize, we just link to it

**Comment by notgull** [comment]
It's mostly just the fact that there's a lot of loading code that can't really be optimized away. I'm not sure if there's a way around this. I've created the `tiny-xlib` library, which only binds to a few functions, as an alternative without this problem.

**Comment by AltF02** [comment]
Yeah smart, is it open source? I might be able to link to it in the README for people with this usecase

**Comment by notgull** [comment]
Yes it is! It's here: https://github.com/notgull/tiny-xlib

**Comment by AltF02** [comment]
Added, closing this issue

**Comment by bolshoytoster** [comment]
I've found that I can save ~60KB by changing
https://github.com/AltF02/x11-rs/blob/ff57a942e5a4d35d8660362a8ca2ac0c02fa4852/x11-dl/src/link.rs#L48-L55

to something like
```rs
[
	$(stringify!($fn_name),)*
	$(stringify!($vfn_name),)*
	$(stringify!($var_name),)*
]
	.try_map(|name| lib.symbol(name))
	.map(|funcs| (lib, ::std::mem::transmute(funcs)))
```

This replaces all of the hundreds of duplicated calls to `DynamicLibrary::symbol` with a single loop producing an array, then transmutes that to the struct.

(That replacment can't be used exactly, since `array::try_map` is unstable)

This is still important, since winit still uses x11-dl, rather than tiny-xlib or xcb.
